services:
  darthvader:
    build: dnsserver
    hostname: darthvader
    ports:
      - 127.0.0.1:53:53    #So na rede principal
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./darthvader/named.conf.options:/etc/bind/named.conf.options
      - ./darthvader/named.conf.local:/etc/bind/named.conf.local
      - ./darthvader/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./darthvader/db.20.168.192:/etc/bind/db.20.168.192

  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 192.168.20.100
    dns: 192.168.20.11

  darthsidious:
    build: dnsserver
    hostname: darthsidious
    depends_on:
      - darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.11

    volumes:
      - ./darthsidious/named.conf.options:/etc/bind/named.conf.options
      - ./darthsidious/named.conf.local:/etc/bind/named.conf.local


networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24


